# Generated by Django 5.0 on 2024-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_berita', models.CharField(max_length=255)),
                ('text_berita', models.TextField()),
                ('gambar_berita', models.ImageField(upload_to='')),
            ],
        ),
    ]
